name: main
on:
  push:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.11"]
        exclude:
        - os: ubuntu-latest
          python-version: 3.10
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 unittest
    - name: Display Python version
      run: python --version
    - name: Check syntax with flake8
      run: flake8 .
    - name: Run tests
      run: python -m unittest
